### ISSUE TITLE
Possible bug in Fortran

### ISSUE THREAD

**Issue by stuartarchibald** [kratzert/RRMPG#1]
Great to see this project using Numba and very pleased to see Numba performing so well :)

I think in this https://github.com/kratzert/RRMPG/blob/master/examples/speed_comparision.ipynb
Cell [4], the `%%fortran` magics declaration has a possible bug.

I'm not sure the Python loop in Cell [3]:
```python
    for i in range(rain.size):
        state_out = (1 - c) * state_in + a * rain[i]
        outflow[i] = (1 - a - b) * rain[i] + c * state_in
        state_in = state_out
```
is quite the same as the Fortran implementation (difference annotated):
```fortran
        state_in = 0
        state_out = 0
        do t = 1,col_dim
            state_out = (1 - c) * state_in + a * inflow(t) !! this assignment is not used and will be dead-code eliminated
            outflow(t) = (1 - a - b) * inflow(t) + c * state_in !! due to state_in always being 0, `c * state_in` is eliminated, (1-a-b) will be hoisted as a loop invariant constant
            state_out = state_in !! again, unused, so DCE.
        end do
```
which I think ends up looking to the compiler like:
```fortran
        do t = 1,col_dim
            outflow(t) = (constant) * inflow(t)
        end do
```
and if one looks at the assembler (`gfortran -O3 -S`):
```asm
.L3:
        movsd   (%r8), %xmm0
        cmpl    $1, %edx
        movl    $2, %edi
        mulsd   %xmm1, %xmm0
        addsd   %xmm2, %xmm0
        movsd   %xmm0, (%r9)
        jbe     .L5
        movsd   8(%r8), %xmm0
        cmpl    $2, %edx
        movb    $3, %dil
        mulsd   %xmm1, %xmm0
        addsd   %xmm2, %xmm0
        movsd   %xmm0, 8(%r9)
        jbe     .L5
        movsd   16(%r8), %xmm0
        cmpl    $3, %edx
        movb    $4, %dil
        mulsd   %xmm1, %xmm0
        addsd   %xmm2, %xmm0
        movsd   %xmm0, 16(%r9)
        jbe     .L5
        movsd   24(%r8), %xmm0
        movb    $5, %dil
        mulsd   %xmm1, %xmm0
        addsd   %xmm2, %xmm0
        movsd   %xmm0, 24(%r9)
.L5:
        cmpl    %edx, %eax
        je      .L1
```
the repeated block:
```asm
        movsd   (%r8), %xmm0
        cmpl    $1, %edx
        movl    $2, %edi
        mulsd   %xmm1, %xmm0
        addsd   %xmm2, %xmm0
        movsd   %xmm0, (%r9)
        jbe     .L5
```
is essentially `outflow(t) = (1 - a - b ) * inflow(t)`, loop unwound with `%r8+offset` as `inflow` and `%r9+offset` as outflow. 

If you also think this is a bug, would be interesting to see how Numba performs against equivalent code.

**Comment by kratzert** [comment]
Ouch, you are totally right. This should be state_in = state_out. I'll change it right now and have a look at the runtime & update the notebook. Thanks for the hint!

**Comment by kratzert** [comment]
Well I guess you might like the answer. Numba now is actually faster then Fortran, although the difference is minimal. But even saying the Numba optimized Python code runs as fast as Fortran is a huge statement!

See: 
- [Notebook](https://github.com/kratzert/RRMPG/blob/master/examples/speed_comparision.ipynb)
- [Docs](http://rrmpg.readthedocs.io/en/latest/examples/speed_comparision.html) also updated

Will also update the corresponding article on my blog.

And thank you very much for this hint and bug report! This motivates me even more to spend time with this project! :)

**Comment by stuartarchibald** [comment]
Great, thanks for the fix. Glad to see Numba match/beat Fortran :) Thanks for supporting Numba!
