### ISSUE TITLE
HBVEdu model: missing attribute area?

### ISSUE THREAD

**Issue by bassoste** [kratzert/RRMPG#11]
Hi,
I am trying to set up an HBVEdu model by using RRMPG.
I follow step by step the procedure illustrated [here](https://rrmpg.readthedocs.io/en/latest/examples/model_api_example.html#) (for another model). However, when I get to the step of fitting, I get the following error:

result = model.fit(cal['QObs(mm/d)'], cal['tmean(C)'], cal['prcp(mm/day)'],
                   cal.index.month.values, long_mean['PET'], long_mean['tmean(C)'])

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-9595bca5e4f8> in <module>
      1 result = model.fit(cal['QObs(mm/d)'], cal['tmean(C)'], cal['prcp(mm/day)'],
----> 2                    cal.index.month.values, long_mean['PET'], long_mean['tmean(C)'])

C:\Anaconda3\envs\rrmpg\lib\site-packages\rrmpg-0.1.1-py3.6.egg\rrmpg\models\hbvedu.py in fit(self, qobs, temp, prec, month, PE_m, T_m, snow_init, soil_init, s1_init, s2_init)
    284         # pack input arguments for scipy optimizer
    285         args = (qobs, temp, prec, month, PE_m, T_m, snow_init, soil_init,
--> 286                 s1_init, s2_init, self._dtype, self.area)
    287         bnds = tuple([self._default_bounds[p] for p in self._param_list])
    288 

AttributeError: 'HBVEdu' object has no attribute 'area'

So, attribute area is missing. My problem is that I cannot understand how I should pass "area" to the model. I tried several things, such as:

area = 100 or
model = HBVEdu(area=100)
 -> no effect

model.set_params(area, 100) or
model.set_params({'area':100})
 -> not working, area is not a parameter (it is not in the list of parameters)

result = model.fit(cal['QObs(mm/d)'], cal['tmean(C)'], cal['prcp(mm/day)'],
                   cal.index.month.values, long_mean['PET'], long_mean['tmean(C)'],
                   snow_init=0.0, soil_init=0.0, s1_init=0.0, s2_init=0.0, area=100)
-> also not working

From the error, I see that the code is searching for self.area, so I believe this should be provided as an attribute of model. But I cannot understand how.
I am not proficient in python, and that is maybe the issue.
I thank you in advance if you can help.

**Comment by kratzert** [comment]
Hi @bassoste,
thanks for bringing up this error. Indeed there was a mistake and I had not removed the obsolete area attribute in the fit function. I already pushed the bugfix, so a simple `git pull` and new install of the package `python setup.py install` should remove the error.

I missed to link this issue in the commit message but here is the commit fixing this bug: https://github.com/kratzert/RRMPG/commit/255224f00d2bdde53666f6bf3f3bf8566de15bb5

Explanation: In the earliest test cases I had the original HBVEdu test data that was not normalized by the basin area, so it had to be done in the fit function. However, my CAMELS loader class already has normalized discharge but I forgot to removed the normalization from this model. Let me know if it runs for you know
