### ISSUE TITLE
Citation and/or acknowledgement

### ISSUE THREAD

**Issue by ckrapu** [kratzert/RRMPG#15]
I've used your implementation of GR4J as a template for a Jax-ified version that I've been using for some applications of MCMC for change detection. [Here's the repo](https://github.com/ckrapu/tvp-gr4j/), for reference. 

Do you have a paper or citable reference I can point to? For now I plan to mention the RRMPG repository in my manuscript.

**Comment by kratzert** [comment]
Hi @ckrapu 

thanks for reaching out and asking how to reference. This repository has no accompanying paper. So as you suggested, I think the only thing that you can reference is the repository itself. That is totally fine for me, and thanks again for asking.

This is a fairly old project that I mainly started to learn about the Numba library. I do not plan to submit it to any journal in the near future, also I could eventually do so (to e.g. JOSS), but it is probably not worth the time. Still happy you found this code and think it is useful!

**Comment by Hulda2002** [comment]
jee n'arrive pas à télécharger GR4j
