### ISSUE TITLE
Where can i get the mean potential evapotranspiration for the other gauges in camels

### ISSUE THREAD

**Issue by chooron** [kratzert/RRMPG#16]
The camels dataset didn't contains the mean potential evapotranspiration (PET) in 'XXX_lump_cida_forcing_leap.txt', but the CemaneigeGR4J needs the input PET. In Model API Example, I found that the example 'PET' data are from the '01031500_05_model_output.txt', so I wonder where can i get the PET data for other gauges.

**Comment by kratzert** [comment]
Hi @chooron 

this is absolutely the wrong place to ask this question. But since I am here, CAMELS contains PET for all basins (I think it is in the model output files). Next time, please check the dataset/paper yourself before posting in an totally unrelated repository.

**Comment by chooron** [comment]
> Hi @chooron
> 
> this is absolutely the wrong place to ask this question. But since I am here, CAMELS contains PET for all basins (I think it is in the model output files). Next time, please check the dataset/paper yourself before posting in an totally unrelated repository.

Thank you for your reply, I have revisited this dataset and found the data I needed, I apologise for any unnecessary trouble my oversight may have caused you.
